# Generated by Django 2.2.4 on 2019-10-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_profile_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/blogpost_files'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null='True', upload_to='media/profile_pic'),
        ),
    ]
