# Generated by Django 2.2.4 on 2019-10-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20191004_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blogpost_files/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null='True', upload_to='profile_pic/'),
        ),
    ]
